version: "2"

services:

  web1804-php5:
    build:
      context: .
      dockerfile: ./1804/Dockerfile
      args:
        - PHP_VERSION=5.3
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      - "3000:80"
      - "3001:3306"
    tmpfs:
      - /var/lib/mysql

  web1804-php5:
    build:
      context: .
      dockerfile: ./1804/Dockerfile
      args:
        - PHP_VERSION=5.3
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      - "3020:80"
      - "3021:3306"
    tmpfs:
      - /var/lib/mysql

  web2004-php5:
    build:
      context: .
      dockerfile: ./2004/Dockerfile
      args:
        - PHP_VERSION=5.3
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      - "3030:80"
      - "3031:3306"
    tmpfs:
      - /var/lib/mysql

  web2004-php5:
    build:
      context: .
      dockerfile: ./2004/Dockerfile
      args:
        - PHP_VERSION=5.3
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      - "3040:80"
      - "3041:3306"
    tmpfs:
      - /var/lib/mysql
